In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [3]:
df = pd.read_csv('cancer_data.csv')
df.head()

Class  age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0      0    5          1           1          1          2          1       3   
1      0    5          4           4          5          7         10       3   
2      0    3          1           1          1          2          2       3   
3      0    6          8           8          1          3          4       3   
4      0    4          1           1          3          2          1       3   

   breast-quad  irradiat  
0            1         1  
1            2         1  
2            1         1  
3            7         1  
4            1         1

In [4]:
df.describe()

Class         age   menopause  tumor-size   inv-nodes   node-caps  \
count  683.000000  683.000000  683.000000  683.000000  683.000000  683.000000   
mean     0.349927    4.442167    3.150805    3.215227    2.830161    3.234261   
std      0.477296    2.820761    3.065145    2.988581    2.864562    2.223085   
min      0.000000    1.000000    1.000000    1.000000    1.000000    1.000000   
25%      0.000000    2.000000    1.000000    1.000000    1.000000    2.000000   
50%      0.000000    4.000000    1.000000    1.000000    1.000000    2.000000   
75%      1.000000    6.000000    5.000000    5.000000    4.000000    4.000000   
max      1.000000   10.000000   10.000000   10.000000   10.000000   10.000000   

        deg-malig      breast  breast-quad    irradiat  
count  683.000000  683.000000   683.000000  683.000000  
mean     3.544656    3.445095     2.869693    1.603221  
std      3.643857    2.449697     3.052666    1.732674  
min      1.000000    1.000000     1.000000    1.000000  
25%      1.000000    2.000000     1.000000    1.000000  
50%      1.000000    3.000000     1.000000    1.000000  
75%      6.000000    5.000000     4.000000    1.000000  
max     10.000000   10.000000    10.000000   10.000000

In [7]:
endog = df['tumor-size'].head(4)
exog =  df[['Class', 'breast', 'node-caps']].head(4)
print(exog)

   Class  breast  node-caps
0      0       3          2
1      0       3          7
2      0       3          2
3      0       3          3


In [8]:
X=exog.to_numpy()
Y= endog.to_numpy()
print(X)

[[0 3 2]
 [0 3 7]
 [0 3 2]
 [0 3 3]]


In [9]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [10]:
M = mean(X.T, axis=1)
print(M)

[0.  3.  3.5]


In [11]:
C= X-M
print(C)

[[ 0.   0.  -1.5]
 [ 0.   0.   3.5]
 [ 0.   0.  -1.5]
 [ 0.   0.  -0.5]]


In [12]:
V = cov(C.T)
print(V)

[[0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         5.66666667]]


In [13]:
values, vectors = eig(V)
print(vectors)
print(values)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.         0.         5.66666667]


In [14]:
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[ 0.   0.  -1.5]
 [ 0.   0.   3.5]
 [ 0.   0.  -1.5]
 [ 0.   0.  -0.5]]


In [15]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents, columns = ['principal component 1'])

In [16]:
exog1 = sm.add_constant(principalDf[['principal component 1']])
print(exog1)

   const  principal component 1
0    1.0                   -1.5
1    1.0                    3.5
2    1.0                   -1.5
3    1.0                   -0.5


In [17]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
model = lm.fit(exog1,endog)
lm.coef_

array([0.        , 0.41176471])

In [18]:
lm.intercept_

3.5

In [19]:
def RSE(y_true, y_predicted):
   
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))

    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [20]:
ypred =lm.predict(exog1)

In [21]:
re = RSE(endog,ypred)
print(re)

3.880570000581328
